AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

inherit_gem:
  foobara-rubocop-rules:
    - rules/*
  # do we want this?
  rubocop-rails-omakase: rubocop.yml

Naming/FileName:
  inherit_mode:
    merge:
      - Exclude
